### PR TITLE
added QFN16 5x5mm 3D model

### PR DESCRIPTION
**Pull request by derwana**
One thing surfaced today while i tried rendering the PCB: the MAX6639's footprint was present but no device on it.

Found the needed 3D model on [3dcontentcentral.com](https://www.3dcontentcentral.com/) and added it to the footprint in the pcb-file. Works like a charm.

### CODE REVIEW

**Comment by volkertb** [comment]
@TheGuyDanish @derwana I still wonder what the licensing deal is with all these assets that we've been adding to the project. Wouldn't that eventually cause problems or conflicts with the chosen CERN license for this project?

**Comment by TheGuyDanish** [comment]
@volkertb It's a valid concern for sure. Most of the models I've put into the project (as well as schematics and footprints, really) are ones that I'm certain I have permission to use. Either through a license agreement with the original creator of that resource, or lack thereof. I can only assume that other contributors extend the same courtesy. In the end, if a manufacturer wants their model removed from the repo, I'll be happy to do that.

**Comment by volkertb** [comment]
Maybe also emphasize in the project LICENSE file that the project's overall license does not necessarily extend and apply to all of the included assets?

**Comment by derwana** [comment]
The README of the CM4_IO board includes the following sentence we may include as well:

> The models provided in the 3dmodels directory are from various manufacturers including Diodes, Hirose, MTCONN,Toby, TRXCOM. Terms and conditions for the use of the models remain with the original manufacture.

As for the models i used from 3dcontentcentral.com they are free to use under the fllowing agreement:

> The Content is provided for the convenience and information of engineers and designers who are designing products that may use similar models as a component, or use similar features and design techniques. Registered Users may view and download the Supplier- and User-supplied Content only for such purposes and not to use the Content on an Internet catalog site or Internet model site. Registered Users may copy and download the Content for model-building purposes provided that the Content provider retains all copyright and other proprietary notices contained in the original Content on any copies of the Content. Registered Users may not modify the Content in any way or reproduce or publicly display, post, transmit, distribute, or otherwise use the Content for any public commercial purpose. Prior to uploading content, the Content provider must agree to terms and conditions for making a contribution, which include granting a right and license to use the content as described in the Terms and Conditions for Contributions.

As we are non commercial i see no problems.

**Comment by TheGuyDanish** [comment]
Adding to the License section in README.md:

> NOTE: Some models, schematics, and/or footprints, are provided by individual manufacturers. As such, all terms and conditions for use, as well as licensing, falls to these original manufacturers. For more information, please inquire with the original component manufacturer or raise an issue here.

**Pull request merged**
