### PR TITLE
Issue #12: Add picture to README to spice things up.

### LINKED ISSUE #12: Show the latest PCB design as a linked image in the README
Just to make the README page a tiny bit more accessible / quickly identifiable—it would be nice to capture [the PDF](https://github.com/TheGuyDanish/CM4_MATX/blob/master/CM4_MATX_PCB.pdf) as an image, and place it on the project's README near the top, linked to the PDF itself, with a note underneath stating the image may be slightly out of date, and to click on the link to the PDF to see the latest design.

See my [Turing Pi Cluster](https://github.com/geerlingguy/turing-pi-cluster) README for an example of how it works (in case you're not familiar with embedding repo images in a README or positioning/aligning them).

Over time we can update the image... and eventually maybe slap a picture of the board itself on it, once it comes to fruition! I will try to help in whatever way I can to make this board a reality, as after a bunch of NAS testing, I'm kinda jealous of all those boring old PC cases being able to mount tons of hard drives without a giant rat's nest of cabling mess.

I'm willing to do this, and will in a bit if nobody else picks this up, but right now I'm putting the kiddos to bed :)

### PR DESCRIPTION
**Pull request by geerlingguy**
Fixes #12.﻿

### CODE REVIEW

**Comment by TheGuyDanish** [comment]
Merging this. In a future commit, I'll probably use the 3D view that KiCad provides to create something a little more tangible for people who might stumble across the repo without any PCB knowledge to look at and fall in love with. For now, though. This is great.

Thanks Jeff!

**Comment by volkertb** [comment]
@geerlingguy Did you document the commands/steps/script that you used to generate the PDF? If it's a script, perhaps you can include it in the repository? I could make use of it for #14.

**Comment by TheGuyDanish** [comment]
@volkertb The PDF was generated from KiCad. When opening the schematic or PCB design in KiCad, you have the option to print.
image
I chose these options, then chose to print it with the "Microsoft Send to PDF" printer that's standard on Windows 10 these days.

**Comment by geerlingguy** [comment]
For my own PR, I just opened the PDF in Preview on my Mac, and exported a JPEG :)

**Pull request merged**
