### PR TITLE
moved PCIe connectors to position

### PR DESCRIPTION
**Pull request by derwana**
Source of measurements is the [Silverstone Motherboard form factor guide](https://www.silverstonetek.com/techtalk_cont.php?area=usa&tid=wh11_008) and in particular [this](https://www.silverstonetek.com/techtalk/11008/pic-7.png) image.

pic-7

### CODE REVIEW

**Comment by TheGuyDanish** [comment]
As always, much appreciated, though this branch is missing the commits from yesterday to put in place the new RJ45 connector. As none of these commits change the schematics, I think we should be good to go if you could put in another commit changing the connector on the PCB to the right one. (If that makes sense) Alternatively, if the changes could be re-done on a freshly-pulled source, that would be a little better.

Let me know if you can do either of those, otherwise, I'm happy to merge it in manually.

**Comment by derwana** [comment]
Yeah – i can do this.

**Comment by derwana** [comment]
Do not merge yet (getting an error on opening the pcb).

**Comment by derwana** [comment]
works now

**Pull request merged**
