### PR TITLE
added schematic of MAX6615 circuitry

### PR DESCRIPTION
**Pull request by derwana**
Please do a proper review before merging (i am kind of a KiCad noobie).

### CODE REVIEW

**Comment by TheGuyDanish** [comment]
I'll review this when I'm off work in a couple hours. Thanks!

**Comment by TheGuyDanish** [comment]
I've got a few bits of trouble in reviewing the schematic side of this, unfortunately. When I try to open any of the schematic files, KiCad throws me an error. At first I thought this was because you were using a newer version of it, but after updating to the latest nightly release, I'm still seeing the same.
image

I can open the PCB, to which I can at least provide a few pointers.

I see you added the R0805 and C0805 footprints to the CM4_MATX footprint library. This is unnecessary. Both of these footprints are available in the Capacitor_SMD and Resistor_SMD libraries that are installed by default with KiCad. Them being in the CM4_MATX library isn't necessarily bad, just a redundancy.

Without seeing the schematics, I can't tell for sure, but I assume JP1 and JP2 are the footprints you've chosen for the Thermistors?

I'm not sure what exactly is causing the schematic to misbehave. I'd say try cloning your own repo and see if you can open them. And if you can open the originals. Any files that weren't touched seem to be fine (other schematic pages, for example)

**Comment by derwana** [comment]
I am going to take a look on it now.

I put the footprints in there to have one library for all the parts used in the project.

JP1 and JP2 are placeholders until a final thermistor is chosen.

**Comment by garlick** [comment]
> I put the footprints in there to have one library for all the parts used in the project.

Considered a best practice by [some](https://hackaday.com/2017/05/18/kicad-best-practises-library-management/).  I was recently hit in one of my projects using kicad v5 with a rename of a C_805 footprint that I had used all over the place.  When cutting and pasting a bypass cap, pcbnew suddenly threw an error about a missing footprint which baffled me for a bit since the same footprint was already in use.  I'm not sure if anything has changed in kicad in v6 in this respect.

**Comment by derwana** [comment]
I am on `kicad-nightly 202011171019` on Ubuntu. I do not get any errors when opening any of the `*.kicad_sch` files.

**Comment by TheGuyDanish** [comment]
Very odd. Grabbing KiCad on my Ubuntu box in a minute.

**Comment by TheGuyDanish** [comment]
image
Some progress I guess. It does make me worried if cross-compatibility between operating systems in KiCad is that flaky.

**Comment by ddkaiser** [comment]
I move projects back and forth between Ubuntu Linux, Mac and Windows using Kicad stable 5.1.x and have never seen an incompatibility.   I think the general advice from the KiCad dev team is that if you intend to use unstable builds such as the nightly builds, you should expect breaking file format issues between versions.  The unstable nightly builds are for KiCad developers as they improve the software, correct?

A question:  Are there features in the 5.99* nightly version which are required for this project, or is there any reason why it could not be produced in a stable 5.1 version of KiCad ?

**Comment by TheGuyDanish** [comment]
Absolutely correct, David. I believe the original reason I ended up with KiCad nightly was because there was some mention of it being the best way to browse the IO board (which I'm starting to doubt now).

It is entirely possible that stable can do everything we need it to, but the question then becomes if we can bring all of our work from nightly to stable, what with the changed file type. (.kicad_pro vs .pro). If not, it'll be a bit of manual work to bring it back to stable, but not impossible. Probably something I'd be able to get done over a weekend.

**Comment by ddkaiser** [comment]
FYI, I loaded the sch and pcb just fine with this version

kicad-nightly  202011171017+7d1a4a422~106~ubuntu20.04.1 amd64

**Comment by TheGuyDanish** [comment]
Yep, same version that's running on my Ubuntu VM. The situation could still be much worse, to be fair. I'll just need to put the time in to get it over to stable instead, unless someone has a good idea for how we could put it into stable without manual labor. ~~Though at this point, I'd be willing to just do it. Gotta own up to my own poor choices. :joy:~~

**Comment by ddkaiser** [comment]
> Considered a best practice by [some](https://hackaday.com/2017/05/18/kicad-best-practises-library-management/).

I agree with Jim G here on the library best-practice.  I have been able to clone others' projects more successfully when they had the Project Library included with the project source.

When having multiple editors working in KiCad, with a shared workspace (i.e. Github), having a 'Project Library' for symbols & footprints is common.  This practice also places these parts under version control (Github) and they "live with the project" as time goes by, leading to easier recovery of old projects.

@TheGuyDanish perhaps you could make the library management conditions part of your CONTRIBUTING doc, i.e. one of these two workflows (or your own)?

Workflow Idea 1 (always use Project Library)
- when placing a symbol or referencing a footprint, only reference the CM4_MATX Project Libraries, and migrate components from standard libraries to the project within the working session.

Workflow Idea 2 (use standard libraries, and 'freeze' components to the project library on release):
- Standard symbols and footprints can come from standard libraries, but if adding a new custom part, it must be in CM4_MATX libraries.
- When moving to tag a release in Github (a major milestone on the project perhaps?) symbols and footprints are copied from the standard locations to the Project Library versions.  There may be some Python scripts to automate some of this, or perhaps the 'Edit Symbol Library Links' and 'Assign Footprints' menu options within eeschema (I've done search/replace copy/paste for these fields on a medium sized, 500 component, project.  It takes some time.)

You could (over time, and as you see fit to do so) add other best practices, for example:
- SCH files must pass ERC before sending in a pull request.  (or exception is noted in the pull request comments)
- PCB files must pass DRC before sending in a pull request.  (or exception is noted in the pull request comments)
- Files must be named as (whatever file-naming standard) i.e. CM4_\<component_name\>   (Looks as this has been done well so far)
- Subsheet files should be in the same directory as the .pro and toplevel .sch file.   (unless you want some contributors work coming in subdirectories...)
- etc.

These things become more important as you move past 4-5 contributors, so choose and implement at your discretion.

These type of practices are used often in distributed software development work, (except the software-team dev practices are: builds must be passing compilation with no errors before checking in a file, files have to follow naming standards, source code requires comments per function, etc.)

**Comment by ddkaiser** [comment]
> unless someone has a good idea for how we could put it into stable without manual labor

@TheGuyDanish I will look to see if there is a solution for this later tonight.  (There's no easy Copy/Paste or Import/Export that will work straight-away though.)

**Comment by TheGuyDanish** [comment]
@ddkaiser I totally agree on having a common library is a great idea. Seeing as this is still a fledgling project (and I'm by no means any kind of engineer, electrician or board designer, I'm a Linux sysadmin by trade), some of these things are just the growing pains in getting everything set up right. Gotta have the infrastructure and rules laid down before we can _really_ get to building something. I do genuinely appreciate all the input that is coming in from this.

I am already playing with the idea of using releases to mark 'official' revisions of the board. (Likely for every step we feel it's progressed enough to do something like a group buy for a number of assembled boards). Doing that would freeze the project's active commit at the time, and if we gather all our schematics and footprints into a single library, that would solve the issue. So I think that would be the best way to go ahead.

Though, I feel we are getting off-topic here just a bit. I'll take your points into consideration the next time I'm updating the CONTRIBUTING.md documentation. I opened #17 for the KiCad Stable situation to continue there. We can revisit this pull request when we have the repo in a better state.

**Comment by derwana** [comment]
So i revisited my drawing and footprints today and found at least one bug (fan connector alignment hole misplaced). Also i am not  as convinced of the MAX6615 anymore. It is a first approach, but i am not satisfied with it. Until "... we have the repo in a better state" i'd dive some deeper into those fan managing ICs.

**Comment by TheGuyDanish** [comment]
Sounds good to me. Do you want to close off this pull request for now and we can revisit the fan control circuitry when the project is in KiCad Stable?

**Comment by derwana** [comment]
Jep – let's close this and do a new approach in KiCad Stable.

**Pull request closed without merging**
