### PR TITLE
Add 3D rendering of PCB. Also add Blender file to allow further tweak…

### PR DESCRIPTION
**Pull request by volkertb**
…ing of the rendering.

3D rendering created by exporting from KiCad to VRML format, and importing it in Blender 2.79 (later versions ignore color on VRML import)
NOTE: KiCad->VRML->Blender export/import/render cycle will have to be repeated each time the PCB design changes visually.

Resolves TheGuyDanish/CM4_MATX#14

### CODE REVIEW

**Comment by volkertb** [comment]
@TheGuyDanish My initial plan was to automate the import and rendering process in the form of a Python script, but the process seemed more complex than I had hoped. Perhaps I or someone else may be able to automate it in the future.

**Comment by TheGuyDanish** [comment]
I really do like the idea of this, but I see a few drawbacks of it.

Firstly, some contributors (myself included) will probably not be downloading Blender just to update the 3D rendering. Meaning someone else would have to do it once the PCB has been updated.
Secondly, the benefit we get from it really is limited. While yes, by itself, it looks slightly better than the KiCad render, it ultimately isn't by much. If there was more of a scene set up where it would benefit from different lighting, and if the models for our components were, well, more than the bare minimum, that would help along the reasoning by quite a bit.

I could see an alternate version of this where someone picks up the mantle of creating these renders and sources better component models. See for example the PCI slots. The x1 slot is the regular model I got from Mouser using Library Loader, while the second is the model I got when I went to Amphenol's website directly. If someone would want to spend some time finding more refined models of each of these components to put on the board and get some nicer pictures, that would be an absolute godsend.

That said, even that, I think would be replaced by a picture of the actual board once we reach a stage at which we can get these produced.

With the above in mind, and in the interest of keeping the repo (relatively) slim. I'd still be happy to merge this without the .blend file. As I mentioned, this is a better look than what we have now.

**Comment by volkertb** [comment]
@TheGuyDanish OK, I removed the Blender file from the Pull Request. It's just the PNG being added to the README now.

By the way, would you like to keep issue #14 open after merging this? If so, I'll have to update the commit message to prevent the issue from being closed with the merge automatically.

**Comment by derwana** [comment]
I'd say keep it open. So we got this in mind for the final product and for anyone who is a 3D artist to see it.

**Comment by volkertb** [comment]
@derwana Okay, I removed the `Resolves` keyword from the commit. It still references the issue, but it shouldn't close it upon merging.

**Comment by TheGuyDanish** [comment]
+1 to derwana's point. Merging.

**Pull request merged**
